### ISSUE TITLE
ReferenceError: d3_vendorSymbol is not defined (only in Firefox)

### ISSUE THREAD

**Issue by gupta-ankit** [humanitiesplusdesign/d3.svg.multibrush#2]
When I use the library in Chrome or Chromium browser, it works fine. However, when I run it in firefox, I get the following error 

    ReferenceError: d3_vendorSymbol is not defined (13:6)

I checked in the d3.svg.multibrush file and I did not find the function definition, only it being called. Is it being declared in some other file.

**Comment by esjewett** [comment]
Will try to look into it in the next couple of week. If you are able to identify a fix and submit a pull request, I'd also be happy to accept that.

**Comment by bbroeksema** [comment]
Can confirm this bug. See e.g. http://syntagmatic.github.io/parallel-coordinates/examples/brushing.html in firefox.

d3_vendorSymbol comes from d3.js, but is not public. More weirdly, in the latest version this actually is a function. Why this only shows up in firefox is a complete mystery to me.

**Comment by bbroeksema** [comment]
I did a very quick and dirty "fix" (I hardly dare to call it like that): https://gist.github.com/bbroeksema/dde0615d9fbb5ef4ca58

This works for me under both firefox and chrome with d3 3.5.5. With one exception: the meta-key is not working anymore. I.e. you can just set multiple brushes by starting a new one on the same axis without any additional keys, Didn't have the time yet to look into that.

Also, I'm not sure if this is the way to go for implementing plugins. As in, I just duplicate some code from d3 in the plugin because it's private. Some input from @mbostock would be appreciate on how to approach this.

**Comment by esjewett** [comment]
@bbroeksema Thanks for looking into this further. Would you be willing to do a pull request with your fix and maybe we can work out the remaining issues?

Regarding duplicating code, I agree it's not the best approach as far as long-term compatibility with d3, but was (and am still) more interested in a quick solution than a perfect one. I don't recall perfectly, but I believe Mike was involved in a discussion around whether it was appropriate to copy this code to build this component and my takeaway was that it was OK as long as it as made clear in the license file that d3 is the source of much of the code (which we have done).

**Comment by bbroeksema** [comment]
Yes, once I find a spare moment to make this happen :). Sorry, the workload is a bit high at the moment.

**Comment by esjewett** [comment]
No worries. Thank you! I'll keep my eye out for it.

On Wed, May 13, 2015 at 4:07 AM, Bertjan Broeksema <notifications@github.com

**Comment by esjewett** [comment]
Is this resolved with the latest pull request? Thank you!

**Comment by bbroeksema** [comment]
Yep, this is the version I'm currently using in my application.

**Comment by esjewett** [comment]
Excellent - then I will close it.
