### ISSUE TITLE
How to prevent overlapping

### ISSUE THREAD

**Issue by satishwaghela** [humanitiesplusdesign/d3.svg.multibrush#8]
![overlapping](https://cloud.githubusercontent.com/assets/8708674/14601553/484277e0-0580-11e6-86f4-89ab647ea91b.png)

**Comment by esjewett** [comment]
Not currently possible. You could certainly modify the library to do this though. We allowed overlapping because it is necessary to allow dragging one selection across another selection, and that is a use-case we want to support for interactive exploration. I'll close this, but if you have further questions, please feel free to ask.

**Comment by satishwaghela** [comment]
Thanks for reply,

I did modification in library and it worked :) . thanks for great library

**Comment by gupta-ankit** [comment]
@satishwaghela  I am trying to do the same. Can you please share your modification to prevent overlap?

**Comment by satishwaghela** [comment]
Hi @gupta-ankit,
Check the [modified code here](https://github.com/satishwaghela/backbone-d3/blob/master/src/js/multibrush.js)
